### ISSUE TITLE
Fehlen von Paketen bei der Beschreibung der Shiny App + Paket "mcr"

### ISSUE THREAD

**Issue by SandraKla** [Bussard91/2021_AdlerMDS_MethodComparisonZlog#5]
Nicht alle Pakete sind in der Readme-Datei aufgeführt.

Ganz wichtig ist vielleicht auch, dass das Paket "mcr" aus CRAN entfernt wurde: https://cran.r-project.org/web/packages/mcr/index.html
Eventuell sollte dies nun ersetzt werden.

**Comment by Bussard91** [comment]
Shit, wusste ich gar nicht. Aber meine App funktioniert noch. Wie geht das? :O

**Comment by SandraKla** [comment]
Wahrscheinlich hast du das Paket damals aus CRAN installiert und es ist immer noch in deiner Biblothek :)

**Comment by Bussard91** [comment]
Aha! na da müssen wir mal gucken wie wir das lösen können...Kennst du Packages die das sonst noch können?

**Comment by n0542344** [comment]
Ich glaube, das Problem hat sich von alleine gelöst - das Projekt wurde doch tatsächlich am 9. November wiederbelebt (also genau zwischen Euren Kommentaren ;).

Zur Not kann man aber auch auf das CRAN Archiv zurückgreifen (siehe [hier](https://cran.r-project.org/src/contrib/Archive/mcr/) für mcr). [Hier](https://stackoverflow.com/questions/24194409/how-do-i-install-a-package-that-has-been-archived-from-cran) ist zudem eine Beschreibung, wie man das machen kann.
