### ISSUE TITLE
Problem bei shinytheme("cosmo")

### ISSUE THREAD

**Issue by SandraKla** [Bussard91/2021_AdlerMDS_MethodComparisonZlog#6]
Komischerweise funktioniert bei mir das shinytheme nicht:

```
Error in shinytheme("cosmo") : 
  cosmo is not an available theme. Valid themes are: .
```

**Comment by Bussard91** [comment]
Irgendwie sind manche themes wirklich komisch. Hatte ich früher auch schonmal. Aber die themes sind wie bei der RI-App wirklich nicht so wichtig. Das kommt zum Ende. Köntne man auch als Dropdown unter einem Settings-Reiter anbieten, da kann jeder User es sich selbst einstellen. Customization bringt Verkäufe. :D

**Comment by SandraKla** [comment]
Oder man kann das Design auch per HTML und CSS verändern (siehe https://github.com/SandraKla/Zlog_AdRI/blob/master/www/style.css)

**Comment by Bussard91** [comment]
Ja das stimmt, ist die Frage: UI konzipieren und dann alles drum herum bauen oder UI am Ende anpassen?

**Comment by n0542344** [comment]
Could not reproduce - ist wahrscheinlich der [hier](https://github.com/rstudio/rstudio/issues/10679) erwähnte Bug der alten Windows-Version von RStudio (siehe auch den [hier](https://stackoverflow.com/questions/71387025/error-r-studio-not-running-shinytheme-theme-yeti-is-not-available-theme) erwähnten SO-Thread).
