### ISSUE TITLE
rio-package zum Data-Import nutzen

### ISSUE THREAD

**Issue by Bussard91** [Bussard91/2021_AdlerMDS_MethodComparisonZlog#7]
Es macht Sinn, das Laden der Daten etwas zu vereinfachen, sodass nicht nur .csv-Dateien geladen werden können sondern auch .xls, .xlsm, .xslx. Hierzu sollte das rio-Package ausprobiert werden.

**Comment by n0542344** [comment]
Ja, gute Idee - habe ich eingebaut.
